apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-serverless
  namespace: test-louis-playground
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: louismaycol/hello-world:v2